[package]
name = "wii"
version = "0.1.0"
edition = "2021"

[dependencies]
libm = "0.2.1"
ogc-rs = { path = "../../../ogc-rs", features = ["ffi"] }
rusttype = { version = "0.9.2", features = ["libm-math"], default-features = false }
void-gfx = { path = "../../void-gfx" }
